name: tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        platform:
          - ubuntu-20.04
          - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Install apt dependencies
        if: ${{ startsWith(matrix.platform, 'ubuntu') }}
        run: |
          sudo apt update
          sudo apt install libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0
          sudo apt install libegl1-mesa libxkbcommon-x11-0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install PyQt6 Markdown pymdown-extensions docutils chardet Pygments
          python -m pip install git+https://github.com/retext-project/pymarkups.git
      - name: Run tests in Xvfb
        if: ${{ startsWith(matrix.platform, 'ubuntu') }}
        run: xvfb-run -a -s "-screen 0 1024x768x24" python -m unittest discover -s tests -v
      - name: Run tests
        if: ${{ !startsWith(matrix.platform, 'ubuntu') }}
        run: python -m unittest discover -s tests -v
  pyflakes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Python dependencies
        run: python -m pip install pyflakes
      - name: Run pyflakes
        run: python -m pyflakes ReText/ tests/ setup.py
